### ISSUE TITLE
KTU installation failed

### ISSUE THREAD

**Issue by Ufungi** [poyuliu/KTU#4]
Hi Po-Yu,

I'm Shinnam Yoo, a beginner in microbiome analysis

After the recent update, I failed to install KTU with the following error comments:

```
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Roxyg ...' is malformed!
```

I tried the following codes for installation:

```
install_github("poyuliu/KTU")
remotes::install_github("poyuliu/KTU")

```

Sincerely, Shinnam Yoo

**Comment by poyuliu** [comment]
Hi Shinnam, 

Thank you for trying out our package!

I've searched for the error message on several forums. Sometimes `install_github` function of the `devtools` package got that error due to a failed connection to GitHub.
The `remotes` package would be an alternative for installing packages. In addition, please check the internet connection without using Proxy.
Or you may try installing the package with this command:
```
library(devtools)
devtools::install_github("poyuliu/KTU", upgrade=FALSE)
```

Cheers,
Po-Yu

**Comment by Ufungi** [comment]
Sorry for the late response.

The installation of KTU package was successful after the reinstallation of R and Rstudio

Thank you.

Sincerely, Shinnam Yoo
